%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Identifiy Indicators of Systemic Risk (2020)
% Benny Hartwig, Christoph Meinering, Yves Schueler
% Deutsche Bundesbank
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all; close all; clc;

addpath('functions')
%% Options
% Import
path_source = strcat(cd,'\');

sheet_imp_opt_all = {'LV_crises',           '1950Q1-2019Q4';... 
                    'LVRR_crises_final',    '1950Q1-2019Q4';... 
                    'ESRB',                 '1950Q1-2019Q4';... 
                    'RGDP',                 '1950Q1-2019Q4';... 
                    'NGDP',                 '1950Q1-2019Q4';... 
                    'CPI',                  '1950Q1-2019Q4';... 
                    'NPPI',                 '1950Q1-2019Q4';... 
                    'RPPI',                 '1950Q1-2019Q4';... 
                    'stock',                '1950Q1-2019Q4';... 
                    'rstock',               '1950Q1-2019Q4';... 
                    'nyields',              '1950Q1-2019Q4';... 
                    'rbondpr',              '1950Q1-2019Q4';... 
                    'spreads',              '1950Q1-2019Q4';...
                    'tcredit',              '1950Q1-2019Q4';... 
                    'rtcredit',             '1950Q1-2019Q4';...
                    'cqgap',                '1950Q1-2019Q4';... 
                    'cqgap_ham',            '1950Q1-2019Q4';...
                    'Mend_cyc',             '1950Q1-2019Q4';... 
                    'Mend_cyc_rt',          '1950Q1-2019Q4';... 
                    'Mend_cyc_1600',        '1950Q1-2019Q4';... 
                    'Mend_cyc_1600_rt',      '1950Q1-2019Q4';...                    
                    'ncab',                 '1950Q1-2019Q4';... 
                    'rcab',                 '1950Q1-2019Q4';... 
                    'cabgdp',               '1950Q1-2019Q4';... 
                    'reer',                 '1950Q1-2019Q4';... 
                    'FCycle',               '1950Q1-2019Q4';... 
                    'FCyc_dreh',            '1950Q1-2019Q4';... 
                    'FCyc_dreh_rt',         '1950Q1-2019Q4';... 
                     };

                    
sheet_name_all = sheet_imp_opt_all(:,1);
sheet_range_all = sheet_imp_opt_all(:,2);

vnames = {'date';'AUS';'AUT';'BEL';'CAN';'DNK';'FIN';'FRA';'DEU';'GRC';'IRL';'ITA';'JPN';'NLD';'NZL';'NOR';'PRT';'ESP';'SWE';'CHE';'GBR';'USA';'BRA';'BGR';'CHL';'CHN';'COL';'CZE';'HKG';'HUN';'IND';'IDN';'ISR';'KOR';'LVA';'MYS';'MEX';'PHL';'POL';'RUS';'SGP';'SVK';'SVN';'ZAF';'THA';'TUR'};
index_data = 2;



excel_name_imp = 'data';
lag_num = [1 4  ,...
    1 4 8 12 ,...
    1 4 8 12,...
    1 4 8 12,...
    1 4,...
    ];
dXlvgroup = {'RGDP','RGDP',...
    'rtcredit','rtcredit','rtcredit','rtcredit',...
    'RPPI','RPPI','RPPI','RPPI',...
    'rstock','rstock','rstock','rstock',...
    'rbondpr','rbondpr'};






for index_sheet = 1 :  length(sheet_name_all)
    sheet_name = sheet_name_all{index_sheet};
    smpl_import = sheet_range_all{index_sheet};
    switch smpl_import
        case '1950Q1-2019Q4'; range_area = 'A1:AT281';
        case '1970Q1-2019Q4'; range_area = 'A1:AT201';
    end
    %% Import data
    [~, ~, raw] = xlsread(strcat(path_source,excel_name_imp,'.xlsx'),sheet_name,range_area);
    mat = raw(index_data:end,2:end);
    vnames_tmp = [{'date'} , raw(1,2:end)];
    date = raw(index_data:end,1);
    mat(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),mat)) = {''};
    
    %% Replace non-numeric cells with NaN
    R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),mat); % Find non-numeric cells
    mat(R) = {NaN}; % Replace non-numeric cells
    mat = reshape([mat{:}],size(mat));
    %% Create output variable
    
    tab.(sheet_name_all{index_sheet}) =  [ table(date) array2table(mat)];
    tab.(sheet_name_all{index_sheet}).Properties.VariableNames = vnames_tmp;
    
    [~ , LOCB] = ismember( vnames_tmp,vnames);
    tab.(sheet_name_all{index_sheet}) =  tab.(sheet_name_all{index_sheet})(:,LOCB);
    %% Clear temporary variables
    clearvars raw R  mat vnames_tmp LOCB;
    
end

%% data transformation



% Construct growth rates: (log difference)



for i = 1 : length(dXlvgroup)
    date = table2array( tab.(dXlvgroup{i})(:,1));
    lag = lag_num(i);
    mat = table2array(tab.(dXlvgroup{i})(:,2:end));
    mat = (log(mat)- log(lagmatrix(mat,lag)))*400/lag;
    tab.(strcat('d',num2str(lag),'l', dXlvgroup{i} )) =  [ table(date) array2table(mat)];
    tab.(strcat('d',num2str(lag),'l', dXlvgroup{i} )).Properties.VariableNames = vnames;
end
clear mat vgroup


save(excel_name_imp,'tab')


