%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Identifiy Indicators of Systemic Risk (2020)
% Benny Hartwig, Christoph Meinering, Yves Schueler
% Deutsche Bundesbank
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

map = [  0 0 1  ; 0.7 0.7 1; ...
                        .8 .8 .8 ; 1 1 1;    0.4 1 0.4;...
                        1 0.7 0.7 ;1 0 0];
ColorLimit = [-2 ; 2];

values = [ 0  -0.5  -1  -2    1 2 ]

width = 12; height = 5;
h = figure('PaperPositionMode', 'auto','Units','inches','Position',[1 1 width height],'renderer','painters','color','w');

xlabel_names = {'Fail Stage 1','Pass Stage 1, fail Stage 2',...
                'Pass Stage 1, Pass Stage 2, $\sum \beta_k <0, \delta_\tau < 0 | \delta < 0$',...
                'Pass Stage 1, Pass Stage 2, $\sum \beta_k <0, \delta_\tau < 0 \& \delta < 0$',...
                'Pass Stage 1, Pass Stage 2, $\sum \beta_k >0, \delta_\tau > 0 | \delta > 0$',...
                'Pass Stage 1, Pass Stage 2, $\sum \beta_k >0, \delta_\tau > 0 \& \delta > 0$'};
ylabel_names = {'Legend'};
heatmap(xlabel_names,ylabel_names,values,...
    'ColorLimits',ColorLimit,'ColorbarVisible','off','GridVisible','off',...
    'Colormap',map,'CellLabelColor','none','MissingDataColor',[0 0 0],'FontSize',14)
